<?php
namespace App\Services; use App\Models\Member; use App\Models\SalesRep; use App\Models\Doctor; use App\Models\Showcase; use App\Models\PointAccount; use App\Models\PointTransaction; use App\Models\PointProduct; use App\Models\RedemptionOrder; use App\Enums\RedemptionOrderStatus; use App\Enums\ProductStatus; use Illuminate\Support\Facades\DB;
class DashboardService {
    public function getCoreStats(): array { $thisMonth = now()->startOfMonth(); return ['member_count' => Member::count(), 'member_this_month' => Member::where('created_at', '>=', $thisMonth)->count(), 'sales_rep_count' => SalesRep::count(), 'doctor_count' => Doctor::count(), 'showcase_count' => Showcase::count(), 'point_account_count' => PointAccount::count(), 'pending_order_count' => RedemptionOrder::where('status', RedemptionOrderStatus::PENDING)->count(), 'low_stock_product_count' => PointProduct::where('stock', '<=', 5)->where('stock', '>', 0)->count()]; }
    public function getPointStats(): array { return ['total_earned' => PointTransaction::where('type', 'earn')->sum('points'), 'total_spent' => PointTransaction::where('type', 'spend')->sum('points'), 'total_refund' => PointTransaction::where('type', 'refund')->sum('points'), 'total_balance' => PointAccount::sum('balance'), 'total_frozen' => PointAccount::sum('frozen_points')]; }
    public function getOrderStats(): array { $thisMonth = now()->startOfMonth(); return ['pending_count' => RedemptionOrder::where('status', RedemptionOrderStatus::PENDING)->count(), 'verified_count' => RedemptionOrder::where('status', RedemptionOrderStatus::VERIFIED)->count(), 'cancelled_count' => RedemptionOrder::where('status', RedemptionOrderStatus::CANCELLED)->count(), 'rejected_count' => RedemptionOrder::where('status', RedemptionOrderStatus::REJECTED)->count(), 'order_this_month' => RedemptionOrder::where('created_at', '>=', $thisMonth)->count(), 'verified_this_month' => RedemptionOrder::where('status', RedemptionOrderStatus::VERIFIED)->where('completed_at', '>=', $thisMonth)->count()]; }
    public function getProductStats(): array { $topProducts = RedemptionOrder::select('point_product_id', DB::raw('count(*) as order_count'))->groupBy('point_product_id')->orderByDesc('order_count')->limit(5)->get()->map(fn($item) => ['name' => PointProduct::find($item->point_product_id)?->name ?? '未知商品', 'order_count' => $item->order_count]); return ['top_products' => $topProducts, 'low_stock_count' => PointProduct::where('stock', '<=', 5)->where('stock', '>', 0)->count(), 'out_of_stock_count' => PointProduct::where('stock', 0)->count(), 'delisted_count' => PointProduct::where('status', ProductStatus::DELISTED)->count()]; }
    public function getRecentTransactions(int $limit = 10): array { return PointTransaction::with('member')->orderByDesc('created_at')->limit($limit)->get()->map(fn($t) => ['id' => $t->id, 'member_name' => $t->member?->name ?? '未知会员', 'member_phone' => $t->member?->phone ?? '', 'type' => $t->type, 'points' => $t->points, 'before_balance' => $t->before_balance, 'after_balance' => $t->after_balance, 'remark' => $t->remark, 'created_at' => $t->created_at->format('Y-m-d H:i:s')])->toArray(); }
    public function getRecentOrders(int $limit = 10): array { return RedemptionOrder::with(['member', 'pointProduct'])->orderByDesc('created_at')->limit($limit)->get()->map(fn($o) => ['id' => $o->id, 'order_no' => $o->order_no, 'member_name' => $o->member?->name ?? '未知会员', 'member_phone' => $o->member?->phone ?? '', 'product_name' => $o->product_name, 'total_points' => $o->total_points, 'status' => $o->status->value, 'status_label' => $o->status->label(), 'created_at' => $o->created_at->format('Y-m-d H:i:s')])->toArray(); }
    public function getShowcaseStats(): array { return ['total' => Showcase::count(), 'authorized' => Showcase::where('authorization_status', 'authorized')->count(), 'wechat_usable' => Showcase::where('usable_for_wechat', true)->count(), 'article_usable' => Showcase::where('usable_for_article', true)->count(), 'xiaohongshu_usable' => Showcase::where('usable_for_xiaohongshu', true)->count(), 'featured' => Showcase::where('is_featured', true)->count()]; }
    public function getRecentShowcases(int $limit = 10): array { return Showcase::with(['doctor', 'member'])->orderByDesc('created_at')->limit($limit)->get()->map(fn($s) => ['id' => $s->id, 'title' => $s->title, 'project_name' => $s->project_name, 'doctor_name' => $s->doctor?->name ?? '-', 'member_name' => $s->member?->name ?? '-', 'authorization_status' => $s->authorization_status, 'authorization_label' => \App\Enums\ShowcaseAuthorizationStatus::from($s->authorization_status)->label(), 'usable_for_wechat' => $s->usable_for_wechat, 'usable_for_article' => $s->usable_for_article, 'usable_for_xiaohongshu' => $s->usable_for_xiaohongshu, 'is_featured' => $s->is_featured, 'created_at' => $s->created_at->format('Y-m-d H:i:s')])->toArray(); }
    public function getFollowUpStats(): array { $followUpService = app(FollowUpService::class); return ['today_pending' => $followUpService->getTodayPendingCount(), 'overdue' => $followUpService->getOverdueCount(), 'month_count' => $followUpService->getMonthFollowUpCount(), 'high_intention' => $followUpService->getHighIntentionCount(), 'month_deal' => $followUpService->getMonthDealCount(), 'sales_counts' => $followUpService->getSalesFollowUpCounts()]; }
    public function getRecentFollowUps(int $limit = 10): array { $followUpService = app(FollowUpService::class); return $followUpService->getRecentFollowUps($limit)->map(fn($f) => ['id' => $f->id, 'member_name' => $f->member?->name ?? '未知会员', 'member_phone' => $f->member?->phone ?? '', 'sales_rep_name' => $f->salesRep?->name ?? '-', 'type' => $f->type, 'type_label' => \App\Enums\FollowUpType::from($f->type)->label(), 'channel' => $f->channel, 'channel_label' => \App\Enums\FollowUpChannel::from($f->channel)->label(), 'intention_level' => $f->intention_level, 'intention_label' => $f->intention_level ? \App\Enums\FollowUpIntentionLevel::from($f->intention_level)->label() : '-', 'status' => $f->status, 'status_label' => \App\Enums\FollowUpStatus::from($f->status)->label(), 'next_follow_at' => $f->next_follow_up_at?->format('Y-m-d H:i'), 'created_at' => $f->created_at->format('Y-m-d H:i:s')])->toArray(); }
    public function getDashboardData(): array { return ['core' => $this->getCoreStats(), 'points' => $this->getPointStats(), 'orders' => $this->getOrderStats(), 'products' => $this->getProductStats(), 'recent_transactions' => $this->getRecentTransactions(), 'recent_orders' => $this->getRecentOrders(), 'showcase' => $this->getShowcaseStats(), 'recent_showcases' => $this->getRecentShowcases(), 'follow_up' => $this->getFollowUpStats(), 'recent_follow_ups' => $this->getRecentFollowUps()]; }
}
