<?php
namespace Tests\Feature; use App\Models\Member; use App\Models\SalesRep; use App\Models\Doctor; use App\Models\Showcase; use App\Services\DashboardService; use Illuminate\Foundation\Testing\RefreshDatabase; use Tests\TestCase;
class ShowcaseWorkflowTest extends TestCase { use RefreshDatabase;
    public function test_can_create_showcase(): void { $doctor = Doctor::create(['name' => '测试医生', 'status' => 1]); $member = Member::create(['name' => '测试会员', 'phone' => '13'.rand(100000000,999999999)]); $salesRep = SalesRep::create(['name' => '测试销售', 'phone' => '13'.rand(100000000,999999999)]);
        $showcase = Showcase::create(['doctor_id' => $doctor->id, 'member_id' => $member->id, 'sales_rep_id' => $salesRep->id, 'title' => '测试案例', 'project_name' => '光子嫩肤', 'project_type' => '光子嫩肤', 'media_type' => 'image', 'authorization_status' => 'authorized', 'content_status' => 'ready', 'is_featured' => true, 'usable_for_wechat' => true, 'usable_for_article' => false, 'usable_for_xiaohongshu' => true, 'status' => 1]);
        $this->assertDatabaseHas('showcases', ['id' => $showcase->id, 'title' => '测试案例']); }
    public function test_showcase_belongs_to_doctor(): void { $doctor = Doctor::create(['name' => '测试医生', 'status' => 1]); $showcase = Showcase::create(['doctor_id' => $doctor->id, 'title' => '测试案例', 'authorization_status' => 'pending', 'status' => 1]); $this->assertEquals($doctor->id, $showcase->doctor->id); }
    public function test_showcase_belongs_to_member(): void { $doctor = Doctor::create(['name' => '测试医生', 'status' => 1]); $member = Member::create(['name' => '测试会员', 'phone' => '13'.rand(100000000,999999999)]); $showcase = Showcase::create(['doctor_id' => $doctor->id, 'member_id' => $member->id, 'title' => '测试案例', 'authorization_status' => 'pending', 'status' => 1]); $this->assertEquals($member->id, $showcase->member->id); }
    public function test_showcase_can_set_authorization_status(): void { $doctor = Doctor::create(['name' => '测试医生', 'status' => 1]); $showcase = Showcase::create(['doctor_id' => $doctor->id, 'title' => '测试案例', 'authorization_status' => 'pending', 'status' => 1]); $showcase->update(['authorization_status' => 'authorized']); $this->assertEquals('authorized', $showcase->fresh()->authorization_status); }
    public function test_showcase_can_set_channel_usage(): void { $doctor = Doctor::create(['name' => '测试医生', 'status' => 1]); $showcase = Showcase::create(['doctor_id' => $doctor->id, 'title' => '测试案例', 'authorization_status' => 'authorized', 'usable_for_wechat' => false, 'usable_for_article' => false, 'usable_for_xiaohongshu' => false, 'status' => 1]); $showcase->update(['usable_for_wechat' => true, 'usable_for_article' => true, 'usable_for_xiaohongshu' => true]); $this->assertTrue($showcase->fresh()->usable_for_wechat); $this->assertTrue($showcase->fresh()->usable_for_article); $this->assertTrue($showcase->fresh()->usable_for_xiaohongshu); }
    public function test_dashboard_can_count_authorized_showcases(): void { $doctor = Doctor::create(['name' => '测试医生', 'status' => 1]); Showcase::create(['doctor_id' => $doctor->id, 'title' => '案例1', 'authorization_status' => 'authorized', 'status' => 1]); Showcase::create(['doctor_id' => $doctor->id, 'title' => '案例2', 'authorization_status' => 'authorized', 'status' => 1]); Showcase::create(['doctor_id' => $doctor->id, 'title' => '案例3', 'authorization_status' => 'pending', 'status' => 1]); $service = app(DashboardService::class); $stats = $service->getShowcaseStats(); $this->assertEquals(2, $stats['authorized']); }
    public function test_dashboard_can_count_wechat_usable_showcases(): void { $doctor = Doctor::create(['name' => '测试医生', 'status' => 1]); Showcase::create(['doctor_id' => $doctor->id, 'title' => '案例1', 'authorization_status' => 'authorized', 'usable_for_wechat' => true, 'status' => 1]); Showcase::create(['doctor_id' => $doctor->id, 'title' => '案例2', 'authorization_status' => 'authorized', 'usable_for_wechat' => true, 'status' => 1]); Showcase::create(['doctor_id' => $doctor->id, 'title' => '案例3', 'authorization_status' => 'authorized', 'usable_for_wechat' => false, 'status' => 1]); $service = app(DashboardService::class); $stats = $service->getShowcaseStats(); $this->assertEquals(2, $stats['wechat_usable']); }
    public function test_doctor_detail_can_query_showcases(): void { $doctor = Doctor::create(['name' => '测试医生', 'status' => 1]); Showcase::create(['doctor_id' => $doctor->id, 'title' => '案例1', 'authorization_status' => 'pending', 'status' => 1]); Showcase::create(['doctor_id' => $doctor->id, 'title' => '案例2', 'authorization_status' => 'pending', 'status' => 1]); $this->assertEquals(2, $doctor->showcases()->count()); }
    public function test_member_detail_can_query_showcases(): void { $doctor = Doctor::create(['name' => '测试医生', 'status' => 1]); $member = Member::create(['name' => '测试会员', 'phone' => '13'.rand(100000000,999999999)]); Showcase::create(['doctor_id' => $doctor->id, 'member_id' => $member->id, 'title' => '案例1', 'authorization_status' => 'pending', 'status' => 1]); $this->assertEquals(1, $member->showcases()->count()); }
} 
